//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCILicitacion.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicitanteLicitacionView
    {
        public long LicitanteId { get; set; }
        public string LicitanteNombre { get; set; }
        public long LicitadorId { get; set; }
        public string LicitadorNombre { get; set; }
        public long LicitacionId { get; set; }
        public string LicitacionNombre { get; set; }
        public string Observaciones { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaCierre { get; set; }
        public System.DateTime FechaAdjudicacion { get; set; }
    }
}
