//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCILicitacion.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicitacionPartidaProductoView
    {
        public long LicitanteId { get; set; }
        public string Licitante { get; set; }
        public long LicitadorId { get; set; }
        public string Licitador { get; set; }
        public long LicitacionId { get; set; }
        public long LicitacionPartidaId { get; set; }
        public long LicitacionPartidaProductoId { get; set; }
        public long ProductoId { get; set; }
        public string ProductoNombre { get; set; }
        public int ProductoCantidad { get; set; }
        public string ProductoObservaciones { get; set; }
        public long ProductoMarcaId { get; set; }
        public string ProductoMarca { get; set; }
    }
}
